### PR TITLE
Added https://bettermarketing.pub/ to list of allowed domains

### PR DESCRIPTION
**Pull request by JaiRelan**
Hey,
This is technically my first open source contribution, so pretty excited here.

Added https://bettermarketing.pub/ on line 68 in the manifest.json file.

Thanks a ton,
Jai

### CODE REVIEW

**Comment by JaiRelan** [comment]
@manojVivek thanks a ton for this extension. Loving it! Please check this PR out

**Comment by nayakayp** [comment]
@manojVivek hei i support this PR. Please add bettermarketing.pub to the list. Thanks a lot!

**Comment by JaiRelan** [comment]
@manojVivek any update?

**Comment by manojVivek** [comment]
Thanks for the PR this is addressed in the https://github.com/manojVivek/medium-unlimited/commit/d1145355375702624f987834a9ba0adad55dea2d commit due to merge conflicts here. 

This went live in v1.10.0. 🎉

**Pull request closed without merging**
